export { default as SentIcon } from './SentIcon';
export { default as PasswordIcon } from './PasswordIcon';
export { default as PlanFreeIcon } from './PlanFreeIcon';
export { default as EmailInboxIcon } from './EmailInboxIcon';
export { default as PlanStarterIcon } from './PlanStarterIcon';
export { default as PlanPremiumIcon } from './PlanPremiumIcon';
export { default as HomeIcon } from './HomeIcon';
export { default as MapIcon } from './MapIcon'
export { default as UpLoadFileIcon } from './UploadFile'
